# Generated by Django 4.2.1 on 2023-07-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_alter_sucursal_options_alter_sucursal_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sucursal',
            table='sucursal',
        ),
    ]
