# Generated by Django 4.2.1 on 2023-07-09 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0004_remove_sucursal_boton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='mapa',
            new_name='map',
        ),
    ]
