# Generated by Django 4.2.1 on 2023-07-09 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0005_rename_mapa_sucursal_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='map',
            new_name='mapa',
        ),
    ]
