# Generated by Django 4.2.1 on 2023-07-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0007_sucursal_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
